[project]
name = "metro-transit-dashboard"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "gtfs-realtime-bindings>=1.0.0",
    "requests>=2.32.3",
    "tabulate>=0.9.0",
]
