[project]
name = "metro-transit-dashboard"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.4",
    "gtfs-realtime-bindings>=1.0.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "requests>=2.32.3",
]
